FROM node:20.9.0 AS builder

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos de dependencias de Node.js
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Construye la aplicación
RUN npm run build

# Expone el puerto 5000
EXPOSE 3020

# Inicia la aplicación
CMD ["npx", "next", "start"]
