version: '3.8'
services:
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
   
    ports:
      - '3001:3000'

    volumes:
      - /app/node_modules
      - .:/app

  server-dev:
    build:
      context: .
      dockerfile: Dockerfile.prod

    ports:
      - '80:80'

    volumes:
      - /app/node_modules
      - ./server:/app

   